const characters = [
  {
    name: "노아 시브라이트",
    max_hp: 100,
    current_hp: 100,
    max_mental: 115,
    current_mental: 115,
    aggressive: 3,
    creativity: 1,
    kindness: 3,
    status: null,
    equipment: null,
  },
  {
    name: "메리제인",
    max_hp: 140,
    current_hp: 140,
    max_mental: 105,
    current_mental: 105,
    aggressive: 5,
    creativity: 2,
    kindness: 1,
    status: null,
    equipment: null,
  },
  {
    name: "후안 살라자르",
    max_hp: 110,
    current_hp: 110,
    max_mental: 105,
    current_mental: 105,
    aggressive: 2,
    creativity: 5,
    kindness: 1,
    status: null,
    equipment: null,
  },
  {
    name: "벅 덴맨",
    max_hp: 150,
    current_hp: 150,
    max_mental: 100,
    current_mental: 100,
    aggressive: 5,
    creativity: 3,
    kindness: 0,
    status: null,
    equipment: null,
  },
  {
    name: "헤일리 데어",
    max_hp: 70,
    current_hp: 70,
    max_mental: 125,
    current_mental: 125,
    aggressive: 2,
    creativity: 1,
    kindness: 5,
    status: null,
    equipment: null,
  },
  {
    name: "미카엘라 에반스",
    max_hp: 110,
    current_hp: 110,
    max_mental: 115,
    current_mental: 115,
    aggressive: 4,
    creativity: 1,
    kindness: 3,
    status: null,
    equipment: null,
  },
  {
    name: "데보라 커닝햄",
    max_hp: 110,
    current_hp: 110,
    max_mental: 115,
    current_mental: 100,
    aggressive: 4,
    creativity: 1,
    kindness: 3,
    status: null,
    equipment: null,
  },
  {
    name: "루크 하퍼",
    max_hp: 150,
    current_hp: 150,
    max_mental: 100,
    current_mental: 100,
    aggressive: 5,
    creativity: 3,
    kindness: 0,
    status: null,
    equipment: null,
  },
  {
    name: "미아 로페즈",
    max_hp: 90,
    current_hp: 90,
    max_mental: 110,
    current_mental: 110,
    aggressive: 1,
    creativity: 5,
    kindness: 2,
    status: null,
    equipment: null,
  },
  {
    name: "헬렌 헤이스",
    max_hp: 90,
    current_hp: 90,
    max_mental: 120,
    current_mental: 120,
    aggressive: 3,
    creativity: 1,
    kindness: 4,
    status: null,
    equipment: null,
  },
  {
    name: "제이크 던트",
    max_hp: 100,
    current_hp: 100,
    max_mental: 110,
    current_mental: 110,
    aggressive: 2,
    creativity: 4,
    kindness: 2,
    status: null,
    equipment: null,
  },
  {
    name: "케이티 하워드",
    max_hp: 140,
    current_hp: 140,
    max_mental: 100,
    current_mental: 100,
    aggressive: 4,
    creativity: 4,
    kindness: 0,
    status: null,
    equipment: null,
  },
  {
    name: "로즈 로저스",
    max_hp: 80,
    current_hp: 80,
    max_mental: 120,
    current_mental: 120,
    aggressive: 2,
    creativity: 2,
    kindness: 4,
    status: null,
    equipment: null,
  },
  {
    name: "사만다 장",
    max_hp: 140,
    current_hp: 140,
    max_mental: 105,
    current_mental: 105,
    aggressive: 5,
    creativity: 2,
    kindness: 1,
    status: null,
    equipment: null,
  },
  {
    name: "클로딘 시모어",
    max_hp: 140,
    current_hp: 140,
    max_mental: 105,
    current_mental: 105,
    aggressive: 5,
    creativity: 2,
    kindness: 1,
    status: null,
    equipment: null,
  },
  {
    name: "데니스 뱌차닌",
    max_hp: 130,
    current_hp: 130,
    max_mental: 100,
    current_mental: 100,
    aggressive: 3,
    creativity: 5,
    kindness: 0,
    status: null,
    equipment: null,
  },
  {
    name: "제인 호프만",
    max_hp: 140,
    current_hp: 140,
    max_mental: 105,
    current_mental: 105,
    aggressive: 5,
    creativity: 2,
    kindness: 1,
    status: null,
    equipment: null,
  },
  {
    name: "센트로 로렌조",
    max_hp: 90,
    current_hp: 90,
    max_mental: 120,
    current_mental: 120,
    aggressive: 3,
    creativity: 1,
    kindness: 4,
    status: null,
    equipment: null,
  },
  {
    name: "데비 한",
    max_hp: 140,
    current_hp: 140,
    max_mental: 100,
    current_mental: 100,
    aggressive: 4,
    creativity: 4,
    kindness: 0,
    status: null,
    equipment: null,
  },
  {
    name: "펠릭스 토레스",
    max_hp: 150,
    current_hp: 150,
    max_mental: 100,
    current_mental: 100,
    aggressive: 5,
    creativity: 3,
    kindness: 0,
    status: null,
    equipment: null,
  },
  {
    name: "아이작 캐터펄트",
    max_hp: 110,
    current_hp: 110,
    max_mental: 110,
    current_mental: 110,
    aggressive: 3,
    creativity: 3,
    kindness: 2,
    status: null,
    equipment: null,
  },
  {
    name: "로버트 월터",
    max_hp: 80,
    current_hp: 80,
    max_mental: 120,
    current_mental: 120,
    aggressive: 2,
    creativity: 2,
    kindness: 4,
    status: null,
    equipment: null,
  },
  {
    name: "션 우즈",
    max_hp: 110,
    current_hp: 110,
    max_mental: 105,
    current_mental: 105,
    aggressive: 2,
    creativity: 5,
    kindness: 1,
    status: null,
    equipment: null,
  },
  {
    name: "헨리 번즈",
    max_hp: 140,
    current_hp: 140,
    max_mental: 100,
    current_mental: 100,
    aggressive: 4,
    creativity: 4,
    kindness: 0,
    status: null,
    equipment: null,
  },
  {
    name: "잭 포말로",
    max_hp: 130,
    current_hp: 130,
    max_mental: 100,
    current_mental: 100,
    aggressive: 3,
    creativity: 5,
    kindness: 0,
    status: null,
    equipment: null,
  },
  {
    name: "카일라 무어",
    max_hp: 110,
    current_hp: 100,
    max_mental: 105,
    current_mental: 105,
    aggressive: 2,
    creativity: 5,
    kindness: 1,
    status: null,
    equipment: null,
  },
];

module.exports = characters;
