const characters = [
  {
    name: "펠릭스 토레스",
    hp: 150,
    mental: 100,
    aggressive: 5,
    creativity: 3,
    kindness: 0,
    status: null,
    equipment: "알루미늄 야구 배트, 절삭 공구",
  },
  {
    name: "케이티 하워드",
    hp: 140,
    mental: 100,
    aggressive: 4,
    creativity: 4,
    kindness: 0,
    status: null,
    equipment: "전기톱, 손도끼",
  },
  {
    name: "헤일리 데어",
    hp: 70,
    mental: 100,
    aggressive: 2,
    creativity: 1,
    kindness: 5,
    status: null,
    equipment: null,
  },
  {
    name: "에이미 미정",
    hp: 90,
    mental: 100,
    aggressive: 2,
    creativity: 3,
    kindness: 3,
    status: null,
    equipment: null,
  },
  {
    name: "루크 하퍼",
    hp: 150,
    mental: 100,
    aggressive: 5,
    creativity: 3,
    kindness: 0,
    status: null,
    equipment: null,
  },
  {
    name: "Character_6",
    hp: 52,
    mental: 64,
    aggressive: 3,
    creativity: 5,
    kindness: 0,
    status: null,
    equipment: null,
  },
  {
    name: "Character_7",
    hp: 64,
    mental: 24,
    aggressive: 1,
    creativity: 1,
    kindness: 0,
    status: "infection",
    equipment: null,
  },
  {
    name: "Character_8",
    hp: 87,
    mental: 2,
    aggressive: 4,
    creativity: 1,
    kindness: 1,
    status: null,
    equipment: null,
  },
  {
    name: "Character_9",
    hp: 86,
    mental: 81,
    aggressive: 1,
    creativity: 1,
    kindness: 0,
    status: "infection",
    equipment: null,
  },
  {
    name: "Character_10",
    hp: 76,
    mental: 90,
    aggressive: 1,
    creativity: 1,
    kindness: 0,
    status: null,
    equipment: null,
  },
  {
    name: "Character_11",
    hp: 63,
    mental: 83,
    aggressive: 1,
    creativity: 1,
    kindness: 0,
    status: null,
    equipment: null,
  },
  {
    name: "Character_12",
    hp: 92,
    mental: 27,
    aggressive: 3,
    creativity: 1,
    kindness: 1,
    status: null,
    equipment: null,
  },
  {
    name: "Character_13",
    hp: 54,
    mental: 21,
    aggressive: 4,
    creativity: 2,
    kindness: 1,
    status: "weakness",
    equipment: null,
  },
  {
    name: "Character_14",
    hp: 56,
    mental: 85,
    aggressive: 1,
    creativity: 5,
    kindness: 2,
    status: null,
    equipment: null,
  },
  {
    name: "Character_15",
    hp: 85,
    mental: 29,
    aggressive: 1,
    creativity: 3,
    kindness: 2,
    status: null,
    equipment: null,
  },
  {
    name: "Character_16",
    hp: 98,
    mental: 5,
    aggressive: 1,
    creativity: 1,
    kindness: 0,
    status: "infection",
    equipment: null,
  },
  {
    name: "Character_17",
    hp: 86,
    mental: 21,
    aggressive: 1,
    creativity: 2,
    kindness: 2,
    status: null,
    equipment: null,
  },
  {
    name: "Character_18",
    hp: 95,
    mental: 57,
    aggressive: 2,
    creativity: 3,
    kindness: 3,
    status: null,
    equipment: null,
  },
  {
    name: "Character_19",
    hp: 69,
    mental: 62,
    aggressive: 1,
    creativity: 1,
    kindness: 0,
    status: "infection",
    equipment: null,
  },
  {
    name: "Character_20",
    hp: 69,
    mental: 9,
    aggressive: 2,
    creativity: 1,
    kindness: 2,
    status: "weakness",
    equipment: null,
  },
  {
    name: "Character_21",
    hp: 53,
    mental: 15,
    aggressive: 4,
    creativity: 1,
    kindness: 1,
    status: null,
    equipment: null,
  },
  {
    name: "Character_22",
    hp: 84,
    mental: 21,
    aggressive: 1,
    creativity: 1,
    kindness: 0,
    status: "infection",
    equipment: null,
  },
  {
    name: "Character_23",
    hp: 90,
    mental: 62,
    aggressive: 2,
    creativity: 5,
    kindness: 1,
    status: null,
    equipment: null,
  },
  {
    name: "Character_24",
    hp: 67,
    mental: 10,
    aggressive: 1,
    creativity: 2,
    kindness: 2,
    status: "weakness",
    equipment: null,
  },
];
module.exports = characters;
