const characters = [
  {
    name: "character1",
    max_hp: 100,
    current_hp: 100,
    max_mental: 115,
    current_mental: 115,
    aggressive: 3,
    creativity: 1,
    kindness: 3,
    status: null,
    equipment: null,
  },
  {
    name: "character2",
    max_hp: 140,
    current_hp: 140,
    max_mental: 105,
    current_mental: 105,
    aggressive: 5,
    creativity: 2,
    kindness: 1,
    status: null,
    equipment: null,
  },
  {
    name: "character3",
    max_hp: 110,
    current_hp: 110,
    max_mental: 105,
    current_mental: 105,
    aggressive: 2,
    creativity: 5,
    kindness: 1,
    status: null,
    equipment: null,
  },
  {
    name: "character4",
    max_hp: 150,
    current_hp: 150,
    max_mental: 100,
    current_mental: 100,
    aggressive: 5,
    creativity: 3,
    kindness: 0,
    status: null,
    equipment: null,
  },
  {
    name: "character5",
    max_hp: 70,
    current_hp: 70,
    max_mental: 125,
    current_mental: 125,
    aggressive: 2,
    creativity: 1,
    kindness: 5,
    status: null,
    equipment: null,
  },
  {
    name: "character6",
    max_hp: 110,
    current_hp: 110,
    max_mental: 115,
    current_mental: 115,
    aggressive: 4,
    creativity: 1,
    kindness: 3,
    status: null,
    equipment: null,
  },
  {
    name: "character7",
    max_hp: 110,
    current_hp: 110,
    max_mental: 115,
    current_mental: 100,
    aggressive: 4,
    creativity: 1,
    kindness: 3,
    status: null,
    equipment: null,
  },
  {
    name: "character8",
    max_hp: 150,
    current_hp: 150,
    max_mental: 100,
    current_mental: 100,
    aggressive: 5,
    creativity: 3,
    kindness: 0,
    status: null,
    equipment: null,
  },
  {
    name: "character9",
    max_hp: 90,
    current_hp: 90,
    max_mental: 110,
    current_mental: 110,
    aggressive: 1,
    creativity: 5,
    kindness: 2,
    status: null,
    equipment: null,
  },
  {
    name: "character10",
    max_hp: 90,
    current_hp: 90,
    max_mental: 120,
    current_mental: 120,
    aggressive: 3,
    creativity: 1,
    kindness: 4,
    status: null,
    equipment: null,
  },
  {
    name: "character11",
    max_hp: 100,
    current_hp: 100,
    max_mental: 110,
    current_mental: 110,
    aggressive: 2,
    creativity: 4,
    kindness: 2,
    status: null,
    equipment: null,
  },
  {
    name: "character12",
    max_hp: 140,
    current_hp: 140,
    max_mental: 100,
    current_mental: 100,
    aggressive: 4,
    creativity: 4,
    kindness: 0,
    status: null,
    equipment: null,
  },
  {
    name: "character13",
    max_hp: 80,
    current_hp: 80,
    max_mental: 120,
    current_mental: 120,
    aggressive: 2,
    creativity: 2,
    kindness: 4,
    status: null,
    equipment: null,
  },
  {
    name: "character14",
    max_hp: 140,
    current_hp: 140,
    max_mental: 105,
    current_mental: 105,
    aggressive: 5,
    creativity: 2,
    kindness: 1,
    status: null,
    equipment: null,
  },
  {
    name: "character15",
    max_hp: 140,
    current_hp: 140,
    max_mental: 105,
    current_mental: 105,
    aggressive: 5,
    creativity: 2,
    kindness: 1,
    status: null,
    equipment: null,
  },
  {
    name: "character16",
    max_hp: 130,
    current_hp: 130,
    max_mental: 100,
    current_mental: 100,
    aggressive: 3,
    creativity: 5,
    kindness: 0,
    status: null,
    equipment: null,
  },
  {
    name: "character17",
    max_hp: 140,
    current_hp: 140,
    max_mental: 105,
    current_mental: 105,
    aggressive: 5,
    creativity: 2,
    kindness: 1,
    status: null,
    equipment: null,
  },
  {
    name: "character18",
    max_hp: 90,
    current_hp: 90,
    max_mental: 120,
    current_mental: 120,
    aggressive: 3,
    creativity: 1,
    kindness: 4,
    status: null,
    equipment: null,
  },
  {
    name: "character19",
    max_hp: 140,
    current_hp: 140,
    max_mental: 100,
    current_mental: 100,
    aggressive: 4,
    creativity: 4,
    kindness: 0,
    status: null,
    equipment: null,
  },
  {
    name: "character20",
    max_hp: 150,
    current_hp: 150,
    max_mental: 100,
    current_mental: 100,
    aggressive: 5,
    creativity: 3,
    kindness: 0,
    status: null,
    equipment: null,
  },
  {
    name: "character21",
    max_hp: 110,
    current_hp: 110,
    max_mental: 110,
    current_mental: 110,
    aggressive: 3,
    creativity: 3,
    kindness: 2,
    status: null,
    equipment: null,
  },
  {
    name: "character22",
    max_hp: 80,
    current_hp: 80,
    max_mental: 120,
    current_mental: 120,
    aggressive: 2,
    creativity: 2,
    kindness: 4,
    status: null,
    equipment: null,
  },
  {
    name: "character23",
    max_hp: 110,
    current_hp: 110,
    max_mental: 105,
    current_mental: 105,
    aggressive: 2,
    creativity: 5,
    kindness: 1,
    status: null,
    equipment: null,
  },
  {
    name: "character24",
    max_hp: 140,
    current_hp: 140,
    max_mental: 100,
    current_mental: 100,
    aggressive: 4,
    creativity: 4,
    kindness: 0,
    status: null,
    equipment: null,
  },
  {
    name: "character25",
    max_hp: 130,
    current_hp: 130,
    max_mental: 100,
    current_mental: 100,
    aggressive: 3,
    creativity: 5,
    kindness: 0,
    status: null,
    equipment: null,
  },
  {
    name: "character26",
    max_hp: 110,
    current_hp: 100,
    max_mental: 105,
    current_mental: 105,
    aggressive: 2,
    creativity: 5,
    kindness: 1,
    status: null,
    equipment: null,
  },
];

module.exports = characters;
